services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: tkarahoksai8528T
      POSTGRES_USER: postgres
      POSTGRES_DB: hoksai
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
